[package]
name = "xailyser-server"
version = "0.0.1"
authors = ["Alex Kovalov <alexkovalevkpi@gmail.com>"]

edition = "2021"
rust-version = "1.84"

categories = ["network-programming"]
keywords = ["networking", "routers", "monitoring"]

readme = "../README.md"
license = "GPL-3"
repository = "https://github.com/xairaven/xailyser"

[dependencies]
crossbeam = "0.8.4"
pnet = "0.35.0"
thiserror = "2.0.11"
toml = "0.8.19"
tungstenite = "0.26.1"
