use serde::{Deserialize, Serialize};

/// IANA: https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub enum IpProtocolField {
    HOPOPT,
    ICMP,
    IGMP,
    GGP,
    IPv4,
    ST,
    TCP,
    CBT,
    EGP,
    IGP,
    BbnRccMon,
    NvpII,
    PUP,
    ARGUS,
    EMCON,
    XNET,
    CHAOS,
    UDP,
    MUX,
    DcnMeas,
    HMP,
    PRM,
    XnsIdp,
    Trunk1,
    Trunk2,
    Leaf1,
    Leaf2,
    RDP,
    IRTP,
    IsoTp4,
    NETBLT,
    MfeNsp,
    MeritInp,
    DCCP,
    _3PC,
    IDPR,
    XTP,
    DDP,
    IdprCmtp,
    TPPlusPlus,
    IL,
    IPv6,
    SDRP,
    Ipv6Route,
    Ipv6Frag,
    IDRP,
    RSVP,
    GRE,
    DSR,
    BNA,
    ESP,
    AH,
    INlsp,
    SWIPE,
    NARP,
    MinIpv4,
    TLSP,
    SKIP,
    Ipv6Icmp,
    Ipv6NoNxt,
    Ipv6Opts,

    AnyHostInternalProtocol,

    CFTP,

    AnyLocalNetwork,

    SatExpak,
    KRYPTOLAN,
    RVD,
    IPPC,

    AnyDistributedFileSystem,

    SatMon,
    VISA,
    IPCV,
    CPNX,
    CPHB,
    WSN,
    PVP,
    BrSatMon,
    SunNd,
    WbMon,
    WbExpak,
    IsoIp,
    VMTP,
    SecureVmtp,
    VINES,
    IPTM,
    NsfnetIgp,
    DGP,
    TCF,
    EIGRP,
    OSPFIGP,
    SpriteRpc,
    LARP,
    MTP,
    Ax25,
    IPIP,
    MICP,
    SccSp,
    ETHERIP,
    ENCAP,

    AnyPrivateEncryptionScheme,

    GMTP,
    IFMP,
    PNNI,
    PIM,
    ARIS,
    SCPS,
    QNX,
    AN,
    IPComp,
    SNP,
    CompaqPeer,
    IpxInIp,
    VRRP,
    PGM,

    AnyZeroHopProtocol,

    L2TP,
    DDX,
    IATP,
    STP,
    SRP,
    UTI,
    SMP,
    SM,
    PTP,
    IsisOverIpv4,
    FIRE,
    CRTP,
    CRUDP,
    SSCOPMCE,
    IPLT,
    SPS,
    PIPE,
    SCTP,
    FC,
    RsvpE2eIgnore,
    MobilityHeader,
    UDPLite,
    MplsInIp,
    Manet,
    HIP,
    Shim6,
    WESP,
    ROHC,
    Ethernet,
    AGGFRAG,
    NSH,
    Homa,
    BitEmu,
    Exp1,
    Exp2,
    Unassigned,
    Reserved,
}

impl From<u8> for IpProtocolField {
    fn from(value: u8) -> Self {
        match value {
            0 => Self::HOPOPT,
            1 => Self::ICMP,
            2 => Self::IGMP,
            3 => Self::GGP,
            4 => Self::IPv4,
            5 => Self::ST,
            6 => Self::TCP,
            7 => Self::CBT,
            8 => Self::EGP,
            9 => Self::IGP,
            10 => Self::BbnRccMon,
            11 => Self::NvpII,
            12 => Self::PUP,
            13 => Self::ARGUS,
            14 => Self::EMCON,
            15 => Self::XNET,
            16 => Self::CHAOS,
            17 => Self::UDP,
            18 => Self::MUX,
            19 => Self::DcnMeas,
            20 => Self::HMP,
            21 => Self::PRM,
            22 => Self::XnsIdp,
            23 => Self::Trunk1,
            24 => Self::Trunk2,
            25 => Self::Leaf1,
            26 => Self::Leaf2,
            27 => Self::RDP,
            28 => Self::IRTP,
            29 => Self::IsoTp4,
            30 => Self::NETBLT,
            31 => Self::MfeNsp,
            32 => Self::MeritInp,
            33 => Self::DCCP,
            34 => Self::_3PC,
            35 => Self::IDPR,
            36 => Self::XTP,
            37 => Self::DDP,
            38 => Self::IdprCmtp,
            39 => Self::TPPlusPlus,
            40 => Self::IL,
            41 => Self::IPv6,
            42 => Self::SDRP,
            43 => Self::Ipv6Route,
            44 => Self::Ipv6Frag,
            45 => Self::IDRP,
            46 => Self::RSVP,
            47 => Self::GRE,
            48 => Self::DSR,
            49 => Self::BNA,
            50 => Self::ESP,
            51 => Self::AH,
            52 => Self::INlsp,
            53 => Self::SWIPE,
            54 => Self::NARP,
            55 => Self::MinIpv4,
            56 => Self::TLSP,
            57 => Self::SKIP,
            58 => Self::Ipv6Icmp,
            59 => Self::Ipv6NoNxt,
            60 => Self::Ipv6Opts,

            61 => Self::AnyHostInternalProtocol,

            62 => Self::CFTP,

            63 => Self::AnyLocalNetwork,

            64 => Self::SatExpak,
            65 => Self::KRYPTOLAN,
            66 => Self::RVD,
            67 => Self::IPPC,

            68 => Self::AnyDistributedFileSystem,

            69 => Self::SatMon,
            70 => Self::VISA,
            71 => Self::IPCV,
            72 => Self::CPNX,
            73 => Self::CPHB,
            74 => Self::WSN,
            75 => Self::PVP,
            76 => Self::BrSatMon,
            77 => Self::SunNd,
            78 => Self::WbMon,
            79 => Self::WbExpak,
            80 => Self::IsoIp,
            81 => Self::VMTP,
            82 => Self::SecureVmtp,
            83 => Self::VINES,
            84 => Self::IPTM,
            85 => Self::NsfnetIgp,
            86 => Self::DGP,
            87 => Self::TCF,
            88 => Self::EIGRP,
            89 => Self::OSPFIGP,
            90 => Self::SpriteRpc,
            91 => Self::LARP,
            92 => Self::MTP,
            93 => Self::Ax25,
            94 => Self::IPIP,
            95 => Self::MICP,
            96 => Self::SccSp,
            97 => Self::ETHERIP,
            98 => Self::ENCAP,

            99 => Self::AnyPrivateEncryptionScheme,

            100 => Self::GMTP,
            101 => Self::IFMP,
            102 => Self::PNNI,
            103 => Self::PIM,
            104 => Self::ARIS,
            105 => Self::SCPS,
            106 => Self::QNX,
            107 => Self::AN,
            108 => Self::IPComp,
            109 => Self::SNP,
            110 => Self::CompaqPeer,
            111 => Self::IpxInIp,
            112 => Self::VRRP,
            113 => Self::PGM,

            114 => Self::AnyZeroHopProtocol,

            115 => Self::L2TP,
            116 => Self::DDX,
            117 => Self::IATP,
            118 => Self::STP,
            119 => Self::SRP,
            120 => Self::UTI,
            121 => Self::SMP,
            122 => Self::SM,
            123 => Self::PTP,
            124 => Self::IsisOverIpv4,
            125 => Self::FIRE,
            126 => Self::CRTP,
            127 => Self::CRUDP,
            128 => Self::SSCOPMCE,
            129 => Self::IPLT,
            130 => Self::SPS,
            131 => Self::PIPE,
            132 => Self::SCTP,
            133 => Self::FC,
            134 => Self::RsvpE2eIgnore,
            135 => Self::MobilityHeader,
            136 => Self::UDPLite,
            137 => Self::MplsInIp,
            138 => Self::Manet,
            139 => Self::HIP,
            140 => Self::Shim6,
            141 => Self::WESP,
            142 => Self::ROHC,
            143 => Self::Ethernet,
            144 => Self::AGGFRAG,
            145 => Self::NSH,
            146 => Self::Homa,
            147 => Self::BitEmu,
            148..=252 => Self::Unassigned,
            253 => Self::Exp1,
            254 => Self::Exp2,
            255 => Self::Reserved,
        }
    }
}
